Renderer profiler 코드리뷰 요청
Hamsik2rang/Kepler pull request #40
Opened 2022-07-12 08:53 UTC by MistarJo

#35 2d rendering 시 데이터를 renderprofiler에 표시하도록 구현하였습니다.
이슈 내 요청이었던 Transferred data(Memory) size은 미구현입니다.
이에 대한 코드 리뷰 요청합니다.

추후 3d rendering 시 데이터를 표시하기 및 다른 데이터(ex. Transferred data(Memory) size) 마저 구현할 예정입니다.

2022-07-12 13:41 UTC, Hamsik2rang reviewed
리뷰 확인 바랍니다.

2022-07-12 13:41 UTC, Hamsik2rang commented on Kepler/Renderer/RenderProfiler.cpp
> +		if (ImPlot::BeginPlot("Plot")) {
여는 중괄호는 다음 줄에 배치합시다.

2022-07-12 13:41 UTC, Hamsik2rang commented on Kepler/Renderer/Renderer2D.cpp
> +				profile.trianglesCount += vt.first.get()->GetIndexBuffer().get()->GetCount() - 2;
raw 포인터를 반드시 이용해야 하는 게 아니면 절대 `.get()`을 호출하면 안 됩니다. smart_ptr의 scope가 깨질 수 있습니다.
`vt.first.get()->GetIndexBuffer().get()->...`
대신 
`vt.first->GetIndexBuffer()->...`
로 사용합시다.

2022-07-12 13:47 UTC, Hamsik2rang commented on Kepler/Renderer/Renderer2D.cpp
> +				profile.trianglesCount += vt.first.get()->GetIndexBuffer().get()->GetCount() - 2;
생각해보니까 예전에 Application::GetWindow()에서 `.get()`으로 날포인터 리턴하는 코드가 있었던 것 같은데 수정할 때 이것도 같이 수정해주면 감사하겠습니다 😅

2022-07-12 14:12 UTC, Hamsik2rang commented
+ 그리고, 애초에 Pull Request가 Merge 전에 코드리뷰를 받는 용도이기 때문에 굳이 리퀘스트 타이틀로 코드리뷰 요청과 같은 언급을 할 필요는 없습니다 😅

2022-07-13 00:51 UTC, MistarJo commented on Kepler/Renderer/RenderProfiler.h
> +		std::unique_ptr<float[]> y_data { new float[size] { 0.0f, } };
`
	struct ImPlotLineData
	{
	public:
		static const int size = 1000;
		std::unique_ptr<float*> x_data;
		std::unique_ptr<float*> y_data;

		ImPlotLineData()
		{
			x_data = std::make_unique<float*>(size);
			for (int i = 0; i < size; i++)
			{
				(*x_data)[i] = 0; //  C2440: '초기화 중': 'const int'에서 'float *'(으)로 변환할 수 없습니다.
				(*y_data)[i] = 0;
				(*x_data.get())[i] = 0; //  C2440: '초기화 중': 'const int'에서 'float *'(으)로 변환할 수 없습니다.
				(*x_data.get())[i] = 0;
			}
		}
	};
`
스마트포인터 배열은 float*, float[]의 의미가 다릅니다. float*로 할 경우 위와 같은 문제가 발생합니다.
혹은 제가 접근 방법을 못 찾는 걸 수도 있습니다.

std::unique_ptr을 사용하는 이유는 x_data, y_data를 앞으로 다른 곳에 소유권을 넘겨줄 필요가 없을 것이라고 생각해서 그렇습니다. struct ImPlotLineData의 코드도 안늘어나고요.

2022-07-13 01:07 UTC, Hamsik2rang commented on Kepler/Renderer/RenderProfiler.h
> +		std::unique_ptr<float[]> y_data { new float[size] { 0.0f, } };
아, 그러네요. 제가 잘못 기억하고 있었네요 🤣
그럼 문제 없습니다.

2022-07-13 01:26 UTC, Hamsik2rang commented
+ 그리고 이건 코드 외 내용인데, submodule로 라이브러리 import할 때 그 라이브러리 저장소 그대로 가져오지 말고 일단 fork한 다음에 fork된 자신의 저장소를 가져오는 게 좋습니다. 원본 라이브러리 브랜치에 새 커밋지점이 생기면 그 커밋을 계속 따라가야 해서 번거로워질 수 있습니다(물론 큰 업데이트가 생기면 fork된 저장소라도 업데이트 커밋을 받아야 합니다).

2022-07-13 01:43 UTC, MistarJo commented on Kepler/Renderer/RenderProfiler.h
> +		static RenderProfiler* s_pInstance;
<img width="506" alt="image" src="https://user-images.githubusercontent.com/51068131/178629788-f2cb1ae6-3e3d-4f34-81c0-733a02d4ee4a.png">

일반 포인터를 delete 할 경우 오류가 생깁니다. 위 이미지는 관련 내용을 검색해본 결과입니다.
스마트 포인터를 쓰거나 delete하지 말라고 하네요.
스마트 포인터를 쓸 경우 현재 PushOverlay()의 파라미터가 Layer*이기 때문에 shard_ptr<Layer>와 호환되지 않습니다.
해결방안
- 스마트 포인터를 쓸 경우 PushOverlay() 에서  .get()을 쓸 수는 있지만 위에서 말씀하신 것 처럼 원시 포인터 리턴이라 안전하지 않습니다.
- 파라미터를 shard_ptr<Layer>로 바꿀 수도 있지만 좀 갈아엎어야겠죠.

2022-07-13 01:46 UTC, Hamsik2rang commented on Kepler/Renderer/RenderProfiler.h
> +		static RenderProfiler* s_pInstance;
오.. 그러네용 PushLayer가 날포인터를 받게 돼있었네요. 그럼 그대로 쓰면 될 것 같아요. 굳이 기존 코드까지 수정하지 맙시다.👍

2022-07-13 01:50 UTC, MistarJo commented on Kepler/Renderer/Renderer2D.cpp
> +				profile.trianglesCount += vt.first.get()->GetIndexBuffer().get()->GetCount() - 2;
<img width="950" alt="image" src="https://user-images.githubusercontent.com/51068131/178631243-25813fa6-b77f-45cd-9ef8-182a719543fa.png">

위 그림의 코드 인 것 같네요.
unique_ptr을 사용하지만 많은 클래스에서 원시 포인터가 공유되고 있습니다.
shard_ptr로 변경하는 것이 좋을까요?

2022-07-13 01:50 UTC, Hamsik2rang commented on Kepler/Renderer/Renderer2D.cpp
> +				profile.trianglesCount += vt.first.get()->GetIndexBuffer().get()->GetCount() - 2;
네. shared_ptr로 바꾸고 함수 내부에서 날포인터 대신 그냥 m_pWindow를 리턴하도록 바꿔주세요. 감사합니다 😊

2022-07-13 02:01 UTC, MistarJo commented
요구사항 반영했습니다.

2022-07-13 02:14 UTC, Hamsik2rang requested changes
RenderProfiler 구조 관련해서 확인 부탁합니다.

Overlay형태로 구현한다면 어차피 모든 오버레이는 한 프레임에서 레이어들보다 이후에 처리되는 게 보장되므로 싱글턴으로 렌더러들이 프로파일러를 아예 호출하지 말고, 프레임 별로 주고 싶은 정보를 저장하다가 프로파일러 업데이트 차례에서 프로파일러만 렌더러한테 Get~()으로 받아오던가, 아니면 다른 객체들처럼 일반 객체를 사용하는 게 나을 수도 있겠네요.

일반 객체로 사용할 경우에 OnGUIRender함수를 호출하는 방법이 고민될 수 있는데, 어차피 프로파일러는 게임에 들어가는 게 아니라 에디터에 들어가는 모듈이라 나중에 Editor GUI를 구현하면 거기서 그려내면 되기 때문에 에디터 모듈이라는 관점에서 레이어보다 이게 더 나을 수도 있습니다.

2022-07-13 02:14 UTC, Hamsik2rang commented on Client/Sources/ClientApp.cpp
> +		PushOverlay(kepler::RenderProfiler::Get());
아까 static ptr delete관련해서 생각하다가 코드 다시 보니까 Push된 Layer나 Overlay는 LayerStack에서 나중에 delete하는 구조라서..

RenderProfiler를 오버레이 형태로 쓰려면 어차피 레이어 객체니까 싱글턴 형식을 포기하거나 아니면 오버레이 형식을 포기하고 '객체'로 써야 할 것 같아요. 다시 확인 부탁합니다.

2022-07-13 06:25 UTC, MistarJo commented
오버레이로 구현하는 방식은 유지하였습니다. 지금 일반 객체로 구현하면 OnGUIRender 문제로 테스트가 곤란합니다. 추후 구현 방법을 변경하는 것이 좋아보입니다.

2022-07-13 07:14 UTC, Hamsik2rang approved these changes
Merge합니다.

2022-07-13 07:14 UTC, Hamsik2rang commented on Kepler/Renderer/RenderProfiler.h
> +		const struct RenderLog* m_profile;
const struct RenderLog* ->const RenderLog*

코드 컨벤션은 그냥 merge하고 수정할게용

2022-07-13 07:14 UTC, merged